# Generated by Django 5.0.6 on 2025-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SITE_ADMIN', 'Site Admin'), ('SHOP_OWNER', 'Shop Owner'), ('SHOPKEEPER', 'Shop Keeper')], default='SHOPKEEPER', max_length=20),
        ),
    ]
