# Generated by Django 5.0.6 on 2025-09-01 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(default='en', max_length=20)),
                ('business_type', models.CharField(default='Kirana / Grocery', max_length=40)),
                ('counter_invoice', models.PositiveIntegerField(default=0)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_rates', models.JSONField(default=list)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='shops.shop')),
            ],
        ),
    ]
