# Generated by Django 5.0.6 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_is_active_shop_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g., +919876543210', max_length=20, null=True),
        ),
    ]
