# Generated by Django 5.0.6 on 2025-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_customer_mobile_invoice_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='oversold',
            field=models.BooleanField(default=False),
        ),
    ]
